// Nomenclature uniformisée Groupe SDG — issue de squelette.xlsx (maquette validée
// avec la DAF) et du mapping actuel de Fanny (codes de l'onglet FX de la balance
// analytique). Les règles sont des données : l'écran admin permet de les compléter.

export type SeedCategory = {
  code: string;
  view: "synthese" | "chantier" | "fx";
  section: string;
  label: string;
  sign: 1 | -1;
  entityScope?: string; // défaut "all"
  notes?: string;
  // règles de mapping : préfixes de comptes, ou exact via { exact: "..." }
  rules: (string | { exact: string })[];
};

export const SECTIONS = {
  synthese: {
    produits: "PRODUITS / CA",
    exploitation: "CHARGES D'EXPLOITATION",
    personnel: "CHARGES DE PERSONNEL",
    fx: "FRAIS GÉNÉRAUX & AUTRES CHARGES",
  },
} as const;

const S = SECTIONS.synthese;

export const seedCategories: SeedCategory[] = [
  // ── SYNTHÈSE — PRODUITS / CA (soldes créditeurs → sign -1 pour affichage positif)
  {
    code: "syn_ca_facturation",
    view: "synthese",
    section: S.produits,
    label: "CA Facturation mois (travaux et prestations)",
    sign: -1,
    rules: ["704", "706"],
    notes: "Comptes différents selon entité (taux TVA, locations, prestations)",
  },
  {
    code: "syn_refacturation",
    view: "synthese",
    section: S.produits,
    label: "Refacturation / Autres CA",
    sign: -1,
    entityScope: "sodobat,vbtp,covarbat",
    rules: ["7088"],
  },
  {
    code: "syn_travaux_encours",
    view: "synthese",
    section: S.produits,
    label: "Travaux en cours (provision M / annulation M-1)",
    sign: -1,
    rules: ["713"],
    notes: "Mécanisme brouillon → figé (réunion 26/06)",
  },
  {
    code: "syn_ventes_marchandises",
    view: "synthese",
    section: S.produits,
    label: "Ventes marchandises",
    sign: -1,
    entityScope: "easymat,easyhome",
    rules: ["707"],
  },
  {
    code: "syn_vente_immo",
    view: "synthese",
    section: S.produits,
    label: "Vente d'immobilisation",
    sign: -1,
    rules: ["757"],
  },
  {
    code: "syn_autres_produits",
    view: "synthese",
    section: S.produits,
    label: "Autres produits (produits de gestion courante)",
    sign: -1,
    rules: ["758"],
  },

  // ── SYNTHÈSE — CHARGES D'EXPLOITATION
  {
    code: "syn_achats_mp",
    view: "synthese",
    section: S.exploitation,
    label: "Achats matières premières (dont emballages)",
    sign: 1,
    rules: ["601", "602"],
  },
  {
    code: "syn_variation_stock",
    view: "synthese",
    section: S.exploitation,
    label: "Variation de stock",
    sign: 1,
    rules: ["603"],
  },
  {
    code: "syn_st_standard",
    view: "synthese",
    section: S.exploitation,
    label: "Sous-traitance standard (TVA 20% / intracomm)",
    sign: 1,
    rules: ["604", "6040"],
  },
  {
    code: "syn_st_autoliq",
    view: "synthese",
    section: S.exploitation,
    label: "Sous-traitance auto-liquidation / TVA 0%",
    sign: 1,
    rules: ["6041"],
  },
  {
    code: "syn_traitement_dechets",
    view: "synthese",
    section: S.exploitation,
    label: "Traitement des déchets",
    sign: 1,
    entityScope: "vbtp,covarbat",
    rules: ["6042"],
  },
  {
    code: "syn_edf_eau",
    view: "synthese",
    section: S.exploitation,
    label: "EDF / Eau (chantier et siège)",
    sign: 1,
    rules: ["6061"],
  },
  {
    code: "syn_gnr_peages",
    view: "synthese",
    section: S.exploitation,
    label: "GNR / Carburant / Péages / Déplacements",
    sign: 1,
    rules: ["60614", "60615", "625"],
  },
  {
    code: "syn_fournitures",
    view: "synthese",
    section: S.exploitation,
    label: "Fournitures / Petit outillage / Vêtements",
    sign: 1,
    rules: ["606"],
  },
  {
    code: "syn_eco_participation",
    view: "synthese",
    section: S.exploitation,
    label: "Éco-participation / Sous-traitance administrative",
    sign: 1,
    rules: ["611"],
  },
  {
    code: "syn_locations",
    view: "synthese",
    section: S.exploitation,
    label: "Locations matériels / bennes / transport",
    sign: 1,
    rules: ["613", "6135"],
  },
  {
    code: "syn_entretien",
    view: "synthese",
    section: S.exploitation,
    label: "Entretien / réparations",
    sign: 1,
    rules: ["615"],
  },
  {
    code: "syn_honoraires_chantier",
    view: "synthese",
    section: S.exploitation,
    label: "Honoraires chantier / Gardiennage",
    sign: 1,
    rules: ["62261", "6282"],
  },

  // ── SYNTHÈSE — CHARGES DE PERSONNEL
  {
    code: "syn_masse_salariale",
    view: "synthese",
    section: S.personnel,
    label: "Masse salariale production (salaires + charges)",
    sign: 1,
    rules: ["64", "633", "791"],
  },
  {
    code: "syn_interims",
    view: "synthese",
    section: S.personnel,
    label: "Intérims / Personnel extérieur",
    sign: 1,
    rules: ["621"],
  },

  // ── SYNTHÈSE — FRAIS GÉNÉRAUX & AUTRES (résumé, détail dans la vue FX)
  {
    code: "syn_fx_credit_bail",
    view: "synthese",
    section: S.fx,
    label: "Crédit-bail / LLD",
    sign: 1,
    rules: ["612"],
  },
  {
    code: "syn_fx_location_immo",
    view: "synthese",
    section: S.fx,
    label: "Locations immobilières et charges locatives",
    sign: 1,
    rules: ["6132", "614"],
  },
  {
    code: "syn_fx_assurances",
    view: "synthese",
    section: S.fx,
    label: "Assurances",
    sign: 1,
    rules: ["616"],
  },
  {
    code: "syn_fx_honoraires",
    view: "synthese",
    section: S.fx,
    label: "Honoraires (SDG, comptabilité, juridique, informatique)",
    sign: 1,
    rules: ["622"],
  },
  {
    code: "syn_fx_sponsoring",
    view: "synthese",
    section: S.fx,
    label: "Sponsoring / Cadeaux / Mécénat / Documentation",
    sign: 1,
    rules: ["618", "623"],
  },
  {
    code: "syn_fx_telecom_banque",
    view: "synthese",
    section: S.fx,
    label: "Téléphone / Frais bancaires / Intérêts / Agios",
    sign: 1,
    rules: ["626", "627", "66"],
  },
  {
    code: "syn_fx_cotisations",
    view: "synthese",
    section: S.fx,
    label: "Cotisations / Frais divers",
    sign: 1,
    rules: ["628"],
  },
  {
    code: "syn_fx_impots",
    view: "synthese",
    section: S.fx,
    label: "Impôts et taxes (CFE, CVAE, foncière…)",
    sign: 1,
    rules: ["63", "635", "637"],
  },
  {
    code: "syn_fx_autres_charges",
    view: "synthese",
    section: S.fx,
    label: "Autres charges (gestion courante, VNC, pénalités)",
    sign: 1,
    rules: ["65", "67"],
  },
  {
    code: "syn_fx_amortissements",
    view: "synthese",
    section: S.fx,
    label: "Dotations aux amortissements et provisions",
    sign: 1,
    rules: ["68"],
  },
  {
    code: "syn_produits_financiers",
    view: "synthese",
    section: S.fx,
    label: "Produits financiers et divers (en déduction)",
    sign: -1,
    rules: ["76"],
  },
  {
    code: "syn_is",
    view: "synthese",
    section: S.fx,
    label: "Impôt Société (IS)",
    sign: 1,
    rules: ["695"],
  },

  // ── ACTIVITÉ CHANTIER — buckets des colonnes du tableau
  {
    code: "cha_facture",
    view: "chantier",
    section: "PRODUITS",
    label: "Facturation (travaux et prestations)",
    sign: -1,
    rules: ["70"],
  },
  {
    code: "cha_tec",
    view: "chantier",
    section: "PRODUITS",
    label: "Travaux en cours (provision / annulation)",
    sign: -1,
    rules: ["713"],
  },
  {
    code: "cha_achats_mp",
    view: "chantier",
    section: "CHARGES",
    label: "Achats matières premières",
    sign: 1,
    rules: ["601", "602", "603", "606"],
  },
  {
    code: "cha_sous_traitance",
    view: "chantier",
    section: "CHARGES",
    label: "Sous-traitance",
    sign: 1,
    rules: ["604"],
  },
  {
    code: "cha_interim",
    view: "chantier",
    section: "CHARGES",
    label: "Intérims / Personnel extérieur",
    sign: 1,
    rules: ["621"],
  },
  {
    code: "cha_personnel",
    view: "chantier",
    section: "CHARGES",
    label: "Charges de personnel affectées",
    sign: 1,
    rules: ["633", "64"],
  },
  {
    code: "cha_autres_charges",
    view: "chantier",
    section: "CHARGES",
    label: "Autres charges directes",
    sign: 1,
    rules: ["6"],
  },
  {
    code: "cha_autres_produits",
    view: "chantier",
    section: "PRODUITS",
    label: "Autres produits affectés",
    sign: -1,
    rules: ["7"],
  },

  // ── FRAIS GÉNÉRAUX (centre analytique FX) — reprend les codes de Fanny
  {
    code: "fx_ms",
    view: "fx",
    section: "MASSE SALARIALE",
    label: "Masse salariale sédentaire (salaires + charges)",
    sign: 1,
    rules: ["64", "633"],
    notes: "Code Fanny 4 — liste nominative à confirmer (question squelette)",
  },
  {
    code: "fx_carburant",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Carburant / Déplacements / Péages / Invitations",
    sign: 1,
    rules: ["60614", "60615", "625", "626"],
    notes: "Codes Fanny 1 et 2",
  },
  {
    code: "fx_edf_eau",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "EDF / Eau (locaux admin)",
    sign: 1,
    rules: ["6061"],
    notes: "Code Fanny 7",
  },
  {
    code: "fx_fournitures",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Fournitures / Petit outillage / Fournitures admin",
    sign: 1,
    rules: ["606", "601", "602"],
    notes: "Code Fanny 6",
  },
  {
    code: "fx_location_immo",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Locations immobilières (SCI Capitou) et charges locatives",
    sign: 1,
    rules: ["6132", "614"],
    notes: "Code Fanny 8",
  },
  {
    code: "fx_location_vehicules",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Location véhicules",
    sign: 1,
    entityScope: "sodobat,easyhome",
    rules: ["6135"],
  },
  {
    code: "fx_entretien",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Entretien / Réparation / Maintenance",
    sign: 1,
    entityScope: "sodobat,vbtp,covarbat",
    rules: ["615"],
    notes: "Code Fanny 11",
  },
  {
    code: "fx_credit_bail",
    view: "fx",
    section: "CRÉDIT-BAIL / LLD",
    label: "Crédit-bail / LLD (ligne globale)",
    sign: 1,
    entityScope: "sodobat,vbtp,covarbat,easymat",
    rules: ["612"],
    notes: "Code Fanny 3",
  },
  {
    code: "fx_assurances",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Assurances (nettes d'indemnités)",
    sign: 1,
    rules: ["616", "7587"],
    notes: "Code Fanny 5 — inclut indemnités d'assurances en déduction",
  },
  {
    code: "fx_honoraires_njw",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Honoraires management NJW / SDG (holding)",
    sign: 1,
    entityScope: "sodobat",
    rules: [{ exact: "62263000" }],
    notes: "Codes Fanny 10/17 — montant fixe mensuel, surveillé par alerte",
  },
  {
    code: "fx_honoraires_divers",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Honoraires divers (comptabilité, juridique, informatique)",
    sign: 1,
    rules: ["622"],
    notes: "Code Fanny 9",
  },
  {
    code: "fx_sponsoring",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Sponsoring / Cadeaux clients / Documentation",
    sign: 1,
    rules: ["623", "618"],
    notes: "Code Fanny 14 (partiel)",
  },
  {
    code: "fx_banque",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Intérêts / Agios / Frais bancaires (nets produits financiers)",
    sign: 1,
    rules: ["627", "66", "76"],
    notes: "Code Fanny 12",
  },
  {
    code: "fx_impots",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Impôts et taxes (CFE, CVAE, foncière…)",
    sign: 1,
    rules: ["63", "635", "637"],
    notes: "Code Fanny 13",
  },
  {
    code: "fx_variation_stock",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Variation stock / Provisions créances douteuses",
    sign: 1,
    rules: ["603", "654", "491"],
    notes: "Code Fanny 15",
  },
  {
    code: "fx_amortissements",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Dotations aux amortissements — VNC",
    sign: 1,
    rules: ["68", "657"],
    notes: "Code Fanny 16",
  },
  {
    code: "fx_autres",
    view: "fx",
    section: "FRAIS GÉNÉRAUX",
    label: "Autres charges et produits divers",
    sign: 1,
    rules: ["628", "658", "758", "671", "65", "67"],
    notes: "Code Fanny 14",
  },
];

export const seedEntities = [
  { code: "sodobat", name: "Sodobat", active: true },
  { code: "easymat", name: "Easy Mat", active: false },
  { code: "easyhome", name: "Easy Home", active: false },
  { code: "vbtp", name: "VBTP", active: false },
  { code: "covarbat", name: "CovarBat", active: false },
];

// Un compte par rôle. Mot de passe par défaut à changer à la mise en production.
export const seedUsers: {
  email: string;
  name: string;
  role: "admin" | "daf" | "lecteur";
}[] = [
  { email: "admin@visionbds.com", name: "Admin", role: "admin" },
  { email: "daf@visionbds.com", name: "DAF", role: "daf" },
  { email: "lecteur@visionbds.com", name: "Lecteur", role: "lecteur" },
];

export const DEFAULT_PASSWORD = "sodobat2026!";
